from __future__ import annotations

import csv
import json
import uuid
from pathlib import Path
from typing import Any

from pydantic import Field

from agent.discovery.memory import (
    DiscoveryMemory,
    DiscoveryReviewDecision,
    VALID_REVIEW_DECISIONS,
    VALID_REVIEW_REASONS,
    now_utc_iso,
)
from agent.models import JsonModel
from agent.utils import write_json


class CurationMemoryUpdateResult(JsonModel):
    status: str
    curation_queue: str
    memory_dir: str
    imported_decision_count: int = 0
    skipped_count: int = 0
    memory_summary: dict[str, Any] = Field(default_factory=dict)
    files: dict[str, str] = Field(default_factory=dict)


def apply_curation_decisions_to_memory(
    *,
    curation_queue: str | Path,
    output_dir: str | Path,
    memory_dir: str | Path = Path("runs") / "discovery_memory",
    decisions_csv: str | Path | None = None,
    default_decision: str | None = None,
    run_id: str = "active_curation",
) -> CurationMemoryUpdateResult:
    """Persist reviewed active-curation items as discovery memory decisions.

    The curation queue is intentionally generated by the recipe stage, while
    DiscoveryMemory is consumed by future discovery scoring.  This adapter keeps
    the two sides decoupled and auditable.
    """

    curation_queue = Path(curation_queue)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    memory = DiscoveryMemory(memory_dir)

    queue_rows = _load_curation_rows(curation_queue)
    decision_lookup = _load_decision_lookup(decisions_csv) if decisions_csv else {}
    default_decision = _normalize_decision(default_decision) if default_decision else ""

    imported: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    decisions: list[DiscoveryReviewDecision] = []
    for index, queue_row in enumerate(queue_rows, start=1):
        row = dict(queue_row)
        curation_id = _curation_id(row, index=index)
        row["curation_id"] = curation_id
        review = _decision_for_row(row, decision_lookup, default_decision)
        if not review:
            skipped.append({**_row_identity(row), "curation_id": curation_id, "skip_reason": "no_review_decision"})
            continue
        decision = _normalize_decision(review.get("decision") or review.get("review_decision") or review.get("verdict"))
        if decision not in VALID_REVIEW_DECISIONS:
            skipped.append(
                {
                    **_row_identity(row),
                    "curation_id": curation_id,
                    "skip_reason": "invalid_review_decision",
                    "raw_decision": review.get("decision") or review.get("review_decision") or review.get("verdict"),
                }
            )
            continue
        project_accession = _clean_text(row.get("project_accession") or review.get("project_accession"))
        file_name = _clean_text(row.get("source_file") or row.get("file_name") or review.get("file_name") or review.get("source_file"))
        if not project_accession or not file_name:
            skipped.append({**_row_identity(row), "curation_id": curation_id, "skip_reason": "missing_project_or_file"})
            continue
        reason = _normalize_reason(
            review.get("reason") or review.get("review_reason") or _default_reason(row.get("curation_type"), decision)
        )
        note = _note_for_row(row, review)
        record = DiscoveryReviewDecision(
            review_id=uuid.uuid4().hex,
            run_id=_clean_text(review.get("run_id") or row.get("run_id") or run_id) or "active_curation",
            created_at=now_utc_iso(),
            repository=_clean_text(row.get("repository") or review.get("repository") or "pride") or "pride",
            project_accession=project_accession,
            file_name=file_name,
            decision=decision,  # type: ignore[arg-type]
            reason=reason,  # type: ignore[arg-type]
            note=note,
        )
        decisions.append(record)
        imported.append(
            {
                **_row_identity(row),
                "curation_id": curation_id,
                "decision": decision,
                "reason": reason,
                "note": note,
                "repository_strategy": _clean_text(row.get("repository_strategy")),
                "planned_repositories": _planned_repositories(row),
                "review_id": record.review_id,
            }
        )

    if decisions:
        memory.append_review_decisions(decisions)
    summary = {
        "schema_version": "curation-memory-update/v1",
        "status": "updated" if decisions else "no_decisions_imported",
        "curation_queue": str(curation_queue),
        "memory_dir": str(memory.root_dir),
        "imported_decision_count": len(imported),
        "skipped_count": len(skipped),
        "imported_decisions": imported,
        "skipped_items": skipped,
        "memory_summary": memory.summary(),
    }
    files = {
        "curation_memory_update_json": str(output_dir / "curation_memory_update.json"),
        "curation_memory_update_csv": str(output_dir / "curation_memory_update.csv"),
        "curation_memory_update_md": str(output_dir / "curation_memory_update.md"),
    }
    write_json(files["curation_memory_update_json"], summary)
    _write_update_csv(Path(files["curation_memory_update_csv"]), imported)
    Path(files["curation_memory_update_md"]).write_text(_markdown_update(summary), encoding="utf-8")
    return CurationMemoryUpdateResult(
        status=str(summary["status"]),
        curation_queue=str(curation_queue),
        memory_dir=str(memory.root_dir),
        imported_decision_count=len(imported),
        skipped_count=len(skipped),
        memory_summary=summary["memory_summary"],
        files=files,
    )


def _load_curation_rows(path: Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload.get("rows") if isinstance(payload, dict) else payload
    if not isinstance(rows, list):
        raise ValueError(f"Invalid curation queue: {path}")
    return [row for row in rows if isinstance(row, dict)]


def _load_decision_lookup(path: str | Path | None) -> dict[str, dict[str, Any]]:
    if not path:
        return {}
    lookup: dict[str, dict[str, Any]] = {}
    with Path(path).open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            clean = {str(key or "").strip(): value for key, value in row.items()}
            keys = _decision_keys(clean)
            for key in keys:
                lookup[key] = clean
    return lookup


def _decision_for_row(row: dict[str, Any], lookup: dict[str, dict[str, Any]], default_decision: str) -> dict[str, Any]:
    for key in _decision_keys(row):
        if key in lookup:
            return lookup[key]
    inline_decision = _normalize_decision(row.get("decision") or row.get("review_decision") or row.get("verdict"))
    if inline_decision:
        return row
    if default_decision:
        return {"decision": default_decision}
    return {}


def _decision_keys(row: dict[str, Any]) -> list[str]:
    curation_id = _clean_text(row.get("curation_id"))
    project = _clean_text(row.get("project_accession"))
    source_file = _clean_text(row.get("source_file") or row.get("file_name"))
    task_type = _clean_text(row.get("task_type"))
    curation_type = _clean_text(row.get("curation_type"))
    keys = [curation_id] if curation_id else []
    if project or source_file or task_type or curation_type:
        keys.append("|".join([project, source_file, task_type, curation_type]))
    return [key for key in keys if key.strip("|")]


def _curation_id(row: dict[str, Any], *, index: int) -> str:
    existing = _clean_text(row.get("curation_id"))
    if existing:
        return existing
    key = "|".join(
        [
            _clean_text(row.get("project_accession")),
            _clean_text(row.get("source_file") or row.get("file_name")),
            _clean_text(row.get("task_type")),
            _clean_text(row.get("curation_type")),
        ]
    ).strip("|")
    return key or f"curation_item_{index:03d}"


def _normalize_decision(value: Any) -> str:
    text = _clean_text(value).lower()
    mapping = {
        "accept": "keep",
        "accepted": "keep",
        "keep": "keep",
        "use": "keep",
        "selected": "keep",
        "reject": "reject",
        "rejected": "reject",
        "exclude": "reject",
        "excluded": "reject",
        "skip": "reject",
        "needs_review": "needs_review",
        "review": "needs_review",
        "unclear": "needs_review",
    }
    return mapping.get(text, text if text in VALID_REVIEW_DECISIONS else "")


def _normalize_reason(value: Any) -> str:
    text = _clean_text(value).lower()
    return text if text in VALID_REVIEW_REASONS else "other"


def _default_reason(curation_type: Any, decision: str) -> str:
    curation_type = _clean_text(curation_type)
    if decision == "keep":
        return "correct"
    if decision == "needs_review":
        return "unclear"
    if curation_type == "confirm_ptm_semantics":
        return "wrong_ptm"
    if curation_type == "confirm_species_policy":
        return "wrong_species"
    if curation_type == "check_leakage_risk":
        return "duplicate"
    if curation_type == "review_metadata_missing":
        return "sdrf_mismatch"
    return "other"


def _note_for_row(row: dict[str, Any], review: dict[str, Any]) -> str:
    planned_repositories = _planned_repositories(row)
    parts = [
        _clean_text(review.get("note")),
        f"curation_type={_clean_text(row.get('curation_type'))}" if row.get("curation_type") else "",
        f"curation_reason={_clean_text(row.get('reason'))}" if row.get("reason") else "",
        f"task={_clean_text(row.get('task_type'))}" if row.get("task_type") else "",
        f"repository_strategy={_clean_text(row.get('repository_strategy'))}" if row.get("repository_strategy") else "",
        f"planned_repositories={','.join(planned_repositories)}" if planned_repositories else "",
    ]
    return "; ".join(part for part in parts if part)


def _planned_repositories(row: dict[str, Any]) -> list[str]:
    raw = row.get("planned_repositories")
    if isinstance(raw, list):
        values = raw
    else:
        values = str(raw or "").replace(";", ",").split(",")
    cleaned: list[str] = []
    seen: set[str] = set()
    for value in values:
        text = _clean_text(value).lower().replace("-", "_")
        if not text:
            continue
        if text in {"px", "proteomexchange"}:
            text = "pride"
        elif text in {"msv", "gnps", "massive_ucsd"}:
            text = "massive"
        elif text == "ipx":
            text = "iprox"
        if text not in seen:
            seen.add(text)
            cleaned.append(text)
    return cleaned


def _row_identity(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "repository": _clean_text(row.get("repository") or "unknown"),
        "project_accession": _clean_text(row.get("project_accession")),
        "file_name": _clean_text(row.get("source_file") or row.get("file_name")),
        "task_type": _clean_text(row.get("task_type")),
        "curation_type": _clean_text(row.get("curation_type")),
    }


def _write_update_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    columns = [
        "curation_id",
        "repository",
        "project_accession",
        "file_name",
        "task_type",
        "curation_type",
        "repository_strategy",
        "planned_repositories",
        "decision",
        "reason",
        "note",
        "review_id",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        for row in rows:
            out = {column: row.get(column) or "" for column in columns}
            out["planned_repositories"] = ";".join(map(str, row.get("planned_repositories") or []))
            writer.writerow(out)


def _markdown_update(summary: dict[str, Any]) -> str:
    lines = [
        "# Curation Memory Update",
        "",
        f"- Status: `{summary.get('status')}`",
        f"- Imported decisions: {summary.get('imported_decision_count', 0)}",
        f"- Skipped items: {summary.get('skipped_count', 0)}",
        f"- Memory dir: `{summary.get('memory_dir')}`",
        "",
    ]
    imported = summary.get("imported_decisions") if isinstance(summary.get("imported_decisions"), list) else []
    if imported:
        lines.append("| Project | File | Task | Curation | Planned repositories | Decision | Reason |")
        lines.append("|---|---|---|---|---|---|---|")
        for row in imported[:25]:
            lines.append(
                "| "
                + " | ".join(
                    _md_cell(value)
                    for value in [
                        row.get("project_accession"),
                        row.get("file_name"),
                        row.get("task_type"),
                        row.get("curation_type"),
                        ", ".join(map(str, row.get("planned_repositories") or [])),
                        row.get("decision"),
                        row.get("reason"),
                    ]
                )
                + " |"
            )
    return "\n".join(lines) + "\n"


def _clean_text(value: Any) -> str:
    return str(value or "").strip()


def _md_cell(value: Any) -> str:
    text = _clean_text(value).replace("|", "\\|")
    return text or "-"
